### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by padalec** [pixers/payum-dotpay#2]
Hi there,
when I try to run this code:
`

        $extension = $container->getExtension('payum');
        $extension->addGatewayFactory(new DotpayGatewayFactory());

        $container->addCompilerPass(new BuildRegistryPass());
        $container->addCompilerPass(new BuildGatewayFactoryPass());
`

this method: addGatewayFactory doeasn't exists and this class new BuildRegistryPass() is deprecated
Can you help me?

**Comment by michallkanak** [comment]
Hi, 
I'm sorry, but this plugin actually supports only "payum/core" in "^1.1.3" version. 
I will update this for new payum version in future

**Comment by padalec** [comment]
Hi,
it's not good information for me so I try to fix this and make PR when done.

**Comment by michallkanak** [comment]
@padalec check please: https://github.com/pixers/payum-dotpay#symfony2---how-to-add-dotpaygateway-v20-for-payum-bundle--20 and let me know how it works now
